services:
   frontend:
      build: ./frontend
      container_name: frontend_services
      ports:
        - "3000:80"
      depends_on:
        - backend

   backend:
      build: ./backend
      container_name: backend_services
      ports:
        - "6000:5000"
      environment:
        - MONGO_URI=mongodb://mongo:27017/Mern
      depends_on:
        - mongo     

   mongo:
      image: mongo:latest
      container_name: mongo_services
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
volumes:
   mongo_data:  